@include('admin.layouts.header')
@include('admin.layouts.navbar')
@include('admin.layouts.sidebar')
@include('admin.layouts.content')
@include('admin.layouts.footer')
@include('admin.layouts.script')
@include('sweetalert::alert')
